version: '3'

services:
  cron:
    image: 'cron'
    environment:
      - TARGET_CRON=
      - TARGET_SCRIPT=
      - TARGET_NAME=
      - NOTIFY_TO=
      - NOTIFY_FROM=
      - NOTIFY_HOST=
      - NOTIFY_USER=
      - NOTIFY_PASS=
      - NOTIFY_STARTTLS=
