version: '3'

services:
  cron:
    image: 'cron'
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file: notify.env
    environment:
      - TARGET_CRON=*/1 * * * *
      - TARGET_SCRIPT=/config/test.sh
      - TARGET_NAME=test
